version: '3.8'

services:
  app:
    build: 
      context: .
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request('http://localhost:3000/health', {timeout: 1000}, (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).end()"]
      interval: 30s
      timeout: 3s
      retries: 3
    # Uses CMD from Dockerfile