version: '3.8'

services:
  app:
    build:
      context: .
      target: builder  # Use builder stage for dev dependencies
    command: npm run dev  # Override production CMD
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI:  ${MONGODB_URL}    # Connection string for MongoDB
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Live code reload
      - /app/node_modules  # Preserve dependencies
      - /app/dist  # Preserve build artifacts
    working_dir: /app
    depends_on:
      - mongodb  # Ensures MongoDB starts first

  mongodb:
    image: mongo:6.0  # Official MongoDB image
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose default MongoDB port
    volumes:
      - mongodb_data:/data/db  # Persistent data storage
    environment:
      MONGO_INITDB_DATABASE: star-core  # Initialize default database

volumes:
  mongodb_data:  # Named volume for data persistence